config/routes.rb
Rails.application.routes.draw do
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  # resources :home, only: [:index]
  # resources :ski, only: [:index]
  get 'home/index' => 'home#index'
  get 'ski/index' => 'ski#index'
  get 'profile/index' => 'profile#index'
  get 'life/index' => 'life#index'
  get 'program/index' => 'program#index'
  get 'inquiry/index' => 'inquiry#index'#入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'#確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'#送信完了画面


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 箱を作りviewを表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/controllers/life_controller.rb
class LifeController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/controllers/program_controller.rb
class ProgramController < ApplicationController
  def index
  end
end

app/controllers/ski_controller.rb
class SkiController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/life_helper.rb
module LifeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/program_helper.rb
module ProgramHelper
end

app/helpers/ski_helper.rb
module SkiHelper
end

app/views/home/index.html.haml
.main
  .main__top
    .main__top-text
  .main__bottom
    .main__bottom-left
      .main__bottom-left__news
        Home
      .main__bottom-left__news__box
        .main__bottom-left__news__top
          .main__bottom-left__news__top__left
            = image_tag ("IMG_8286.PNG");
          .main__bottom-left__news__top__right
            %p 国内外のスキーの大会に出場したりしています
            %p スキーが大好きです
        .main__bottom-left__news__middle
          .main__bottom-left__news__middle__text
            %p プログラミングでウェブサービスを開発しています
          .main__bottom-left__news__middle__photo
            = image_tag ("code-kids2.png");
    .main__bottom-right
      .main__bottom-right__photo
        .main__bottom-right__photo__image
          = image_tag("IMG_0809.JPG");
      .main__bottom-right__name
        %p
          勝野天欄
      .main__bottom-right__me
        %p
          tech-expert 53期生 
        %p プログラミング修行中
        %p スキーの方では選手として活動していて、国内外の大会にも出場しています
      .main__bottom-right__box
        .top
          .insta
            = link_to ("https://www.instagram.com/tenra_katsuno123/") do
              %i.fab.fa-instagram
          .facebook
            = link_to ("https://www.facebook.com/Tenra-Katsuno-843361695788556/") do
              %i.fab.fa-facebook-square
        .bottom 
          .youtube
            = link_to ("https://www.youtube.com/channel/UCaQ0xGWuItQey6cJ7NVS8jg?view_as=subscriber") do
              %i.fab.fa-youtube
          .twitter 
            %i.fab.fa-twitter
        = link_to("/inquiry/index") do
          %p お問い合わせ
      

  

app/views/inquiry/confirm.html.haml
.newWrap
  .newTitle
    %h1 お問い合わせ：確認
  .newContent
    = form_for @inquiry, :url => inquiry_thanks_path do |f|
      .row
        .col-sm-4 名前
        .col-sm-8
          = f.hidden_field :name
          = @inquiry.name
        .col-sm-4 メールアドレス
        .col-sm-8
          = f.hidden_field :email
          = @inquiry.email
        .col-sm-4 お問い合わせ内容
        .col-sm-8
          = f.hidden_field :message
          = simple_format(@inquiry.message)
      = f.submit '送信する', class: 'btn btn-block btn-success'

app/views/inquiry/index.html.haml
- @page_title = 'お問い合わせ'
.newWrap
  .newTitle
    %h1 お問い合わせ
  .newContent
    = form_for @inquiry, :url => inquiry_confirm_path do |f|
      - if @inquiry.errors.any?
        .alert.alert-danger{:role => "alert"}
          %strong 入力内容にエラーがあります
          %ul
            - @inquiry.errors.each do |attr, msg|
              %li= msg
      .row
        .col-sm-4
          名前
          %span.text-danger （必須）
        .col-sm-8= f.text_field :name, class: 'form-control mb-2'
        .col-sm-4
          メールアドレス
          %span.text-danger （必須）
        .col-sm-8= f.text_field :email, class: 'form-control mb-2'
        .col-sm-4 お問い合わせ内容
        .col-sm-8= f.text_area :message, class: 'form-control mb-2', rows: '6'
      = f.submit '確認', class: 'btn btn-block btn-success'

app/views/inquiry/thanks.html.haml
.newWrap
  .newTitle
    %h1 お問い合わせ：送信しました
  .newContent
    %p お問い合わせありがとうございます。

app/views/layouts/application.html.haml
!!!
%html{lang: "ja"}
  %head
    %meta{content:"text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{content:"width=device-width, initial-scale=1.0", name: "viewport"}/
    %link{:href => "css/font-awesome.min.css", :rel => "stylesheet"}/
    %title Tenlife
    = stylesheet_link_tag    'application', media: 'all'
  .wrapper
    %body
      .pop
        %h1 
          = link_to "/home/index", class: "gg" do
            Tenlife
        .top__text-box
          %h2
            = link_to "https://tenlife123.com/", class: "fi" do
              Blog
          %h2
            = link_to "/profile/index", class: "fi" do
              Profile
          %h2
            = link_to "/ski/index", class: "sk" do
              Ski
          %h2
            = link_to "/program/index", class: "pr" do
              Programing
          %h2
            = link_to "/home/index", class: "hm" do
              Home
          
      .header
        = image_tag("IMG_3236.JPG")
        .header__left
          -# %h1
          -#   = link_to "/home/index", class: "hm" do
          -#     home
          -# %h1
          -#   = link_to "/ski/index", class: "sk" do
          -#     ski
          -# %h1
          -#   = link_to "/program/index", class: "pr" do
          -#     programing
          -# %h1
          -#   = link_to "/profile/index", class: "fi" do
          -#     profile
        .header__right




    = yield

app/views/life/index.html.haml
.about-life
  %h2 写真かテキスト
  %p こんにちわ
.skil
  .skil__show
    %h2 私の趣味
    .skil__list
      %li スキー
      %li 旅
      %li プログラミング
      %li サッカー
      %li トランポリン
.life
  .life__time
    .life__time-text
      %p
        ooooooooooooffffffffffoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhoooooffooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
    .life__time-photo
      写真
  .life__show
    .life__show-photo
      写真
    .life__show-text
      %p
        uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyynnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnyyyyyyyyyyyyyyuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu

app/views/program/index.html.haml
.about-code
  %h1 Programing
  = image_tag("business-3152586_1280.jpg");
  .gard
    %p webサービスの開発もやってます。今はtech-expertで修行中
.skilll
  .show__skilll
    .cover-image
      = image_tag("IMG_0809.JPG")
    .skilll__list
      %h1 スキル
      %li html/css
      %li ruby on rails
      %li python
      %li php
.programing
  .code
    .code__text-code
      %h1 最近の成果
    .program__text-sentense
      = image_tag("chat-space.png");
        

app/views/ski/index.html.haml
.about-ski
  %h1 Ski
  .press
    -# = image_tag("IMG_3041 2.JPG");
    = image_tag("FJWC19_KAPPL_SVOITL_BS1_0039.jpg");
    %p ⬅️日本人として初めて招待された大会  (大会MVP賞獲得)
.skill
  .show__skill
    .cover-img
      = image_tag("IMG_0809.JPG")
    .skill__list
      %h1 使用マテリアル
      %li スキー Salomon Qst 106
      %li ブーツ Salomon Xmax pro 130
      %li ウェア Salomon 
      %li ゴーグル Salomon Lo-Fi
      %li グローブ Salomon 
.ski
  -# %p この時は日本人1人
  .comp
    .comp__text-ski
      %h1 国内外でフリーライドスキーヤーとして、大会や撮影を行なっています。
      -# %h1 2016~2017
      -# %p Kiroro Powder Freeride 1st
      -# %p なまら一発 2nd
      -# %p hanazono slopestyle 2nd
      -# %p Japan Freeride Open Four runner

      -# %h1 2017~2018
      -# %p Japan Freeride Open 7th 
      -# %p Powder Freeride Kiroro 1st
      -# %p NZJFT remarks 3rd
      -# %p NZJFT Mt.Olympus 6th
      -# %p NZJFT Mt.Rupehu 6th & Move of the day
      -# %p Freeride Junior World Championship   Move of the day
      -# %p Over all ranking 24th

      -# %h1 2018~2019
      -# %p NZJFT Remarks 3rd
      -# %p NZJFT Mt.Olympus 3rd
      -# %p NZJFT Mt.Ruapehu 3rd
      -# %p Freeride World Qualifire  Four runner
      -# %p Japan Freeride Open 8th
      -# %p FJT Eldorado 11th
      -# %p FJT Nendaz 31th
      -# %p FJWC Kappl 8th
      -# %p FJT Verbier 10th
      -# %p Over all ranking 12th
    .comp__photo-ski
      = image_tag("IMG_3041 2.JPG");
  -# .free
  -#   .free__ski-photo
  -#     写真
  -#   .free__ski-text
  -#     %p
  -#       uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyynnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnyyyyyyyyyyyyyyuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu